version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: 'etl_db'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pim_export
      - MYSQL_PASSWORD=root
      - PMA_ARBITRARY=1
      - PMA_HOST=
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    networks:
      - etl
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'etl_state_manager'
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_VHOST=etl-state-manager-queue'
    networks:
      - etl
    depends_on:
      - mysql

volumes:
  mysql_data: {}

networks:
  etl: {}
